<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>738df038-ac20-4746-ae67-47465d1b547c</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[ add a new Claim Medical Wastage Acceptability List where
      the Message is "Unacceptable Medical Wastage." , 
      the Output is Unacceptable to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
