<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>SIX Month Lookback Threshold Date</name>
  <uuid>a7e3959e-026b-40fe-affe-29176df7ab42</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	the Run Date of System is not null 
then
	set decision to the date of the Run Date of System - 6 months ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
