<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Past 12 Months Claim Count</name>
  <uuid>61d0aa5a-1a5e-43d4-9dfb-8c28b3b27451</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the number of elements in 'Past 12 Months Claim Collect' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
