<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Diagnosis Code</name>
  <uuid>b06384c0-8b94-43a7-ba0c-a61e134c0366</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[ definitions 
	set 'Diagnosis' to a Diagnosis  Code List in 'Diagnosis Code List' ; 
    then 
	add  the Code of Diagnosis to decision ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
