<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Treatment Code Count</name>
  <uuid>1ce294e2-d3fa-492c-ab5a-967635a99b9a</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the number of elements in 'Treatment Code' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
