<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>052457f8-5880-40f5-b716-3574c48e6cee</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[add None Of The Above to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
