<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Diagnosis Code Count</name>
  <uuid>b8a5bccf-417d-4535-8bff-18a85f03b711</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the number of elements in 'Diagnosis Code' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
