<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>ae5fbe3d-0979-4a5d-8a98-4e1e1c9efdfb</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[add None to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
