<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>b0d5c650-e80f-40e3-9f73-9896bbc39ee2</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[add Decline to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
