<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Claim Age in Days</name>
  <uuid>c33315dd-3e5e-43f4-b6ae-9f22ef833f0b</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[ definitions 
	set 'aClaim' to a Claim in Claims ; 
     then 
	add the number of days between the RunDate of System and the Date of aClaim to decision  ; 
    ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
