<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>bf38154c-5daf-4027-a843-d9cac80bd379</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[add a new Length of Stay Percentile List where
		the Lengh of Stay 50th Percentile List is 0 , 
		the Lengh of Stay 75th Percentile List is 0 , 
		the Lengh of Stay 90th Percentile List is 0 to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
