<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>10dbd997-2705-46d1-a56d-c059354b067d</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new Claim Cost Reasonableness where
		the Message is "No Message" , 
		the Output is None Of The Above ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
